# -*- coding: utf-8 -*-
"""第四章  技术和功能创新 — 作品设计实现方案正文。"""
from __future__ import annotations

SECTIONS = [
    {
            "level": 1,
            "title": '第四章  技术和功能创新',
            "paragraphs": [
                '本章在前三章系统架构与实现基础上，集中阐述「执图破局」相对业界常见技术路线与三类基线方案的技术与功能创新。论述采用学术评审口径：先对比分析，再分模块展开创新机制，最后给出可定位源码、可复核公式、可对照测试的Innovation 清单（I1—I5）。全章不涉及答辩演示脚本，侧重评委对创新真实性、必要性与先进性的书面审查。',
                '对比对象包括：（1）Neo4j 图数据库 + LangChain Agent 编排 + Vue 单页应用的主流知识图谱工程栈；（2）传统 HR 关键词匹配与技能标签重合方案；（3）纯大语言模型报告生成方案。三类基线分别代表「图链前端全栈」「浅层检索匹配」「生成式 AI 叙事」三种典型路径，与赛题 XH-202621 强调的多源治理、动态演化、可验证匹配形成对照。',
                '本章结构如下：4.1 节从宏观优势与技术创新的总览对比入手，含表 4.1；4.2 节阐述发现—演化—匹配闭环；4.3 节阐述模块化研判工作台；4.4 节阐述数据治理与可信 AI；4.5 节阐述图谱可视化与态势分析。各节段落均可与 backend/、frontend/ 源码及第五章测试指标交叉验证。',
                '创新论述的评判标准对齐揭榜挂帅赛题：是否解决多源异构数据质量问题、是否支撑新兴岗位科学发现、是否量化能力动态演化、是否实现可解释人岗匹配、是否在大模型增强下保持结论可建档与低幻觉。五项 I1—I5 创新即按此五问组织，而非简单罗列功能清单。',
                '需要说明的是，技术选型对比并非否定 Neo4j、LangChain 或 Vue 的固有价值，而是在本赛题给定的时间、团队与评测约束下，对「可现场复现、可源码审查、可指标对照」优先级的工程化表达。文档第六章已保留向 Neo4j 子图同步扩展的路径，体现演进空间。',
                '下文将依次展开各节创新论述；建议评委阅读本章时对照《启动指南》本地部署系统，并在 OpenAPI /docs 与 pytest 测试集中抽检创新点声称与运行行为的一致性。',
            ],
        },
    {
            "level": 2,
            "title": '4.1  项目优势分析',
            "paragraphs": [],
        },
    {
            "level": 3,
            "title": '4.1.1  项目对比分析',
            "paragraphs": [
                '赛题解读与业界常见方案中，「Neo4j 图数据库 + LangChain Agent 编排 + Vue 单页应用」被视为知识图谱类项目的标准技术栈。该组合在关系查询、对话式交互与组件化前端方面具备成熟生态，但在揭榜挂帅现场评测场景下，存在部署链路长、推理过程黑盒化、结论难以指回原始 JD 证据等工程短板。执图破局在立项阶段对该路线进行了对照原型评估，最终选择以 PostgreSQL 关系模型承载岗位—技能共现与聚合查询，以原生 HTML/CSS/JavaScript 实现多页研判界面，以可回放 DiscoveryAgent 替代纯 LangChain 链式调用，在保持图谱语义表达力的同时，显著降低评委复现成本并增强结论可审计性。',
                '与关键词匹配方案相比，本项目不将「技能标签字面重合」作为唯一决策依据。传统 TF-IDF、布尔检索或 HR 系统内置的关键词过滤器对「AI Agent 架构师」「RAG 系统工程师」等尚未进入标准职业分类的新兴岗位名称识别率极低，且无法给出新兴度量化评分与演化速度信号。执图破局通过 PG 语料聚类、技能共现图与五维新兴度模型，将「词面未命中但语义簇已形成」的候选岗位纳入可解释发现池；相较关键词方案，在 23 类专家标注新兴岗上的 Recall 由约 0.41 提升至 0.913，F1 达 0.824。',
                '与纯 LLM 报告生成方案相比，本项目严格区分「生成增强层」与「结构化结论层」。若直接将 DeepSeek 等大模型用于新兴岗位定义入库而不绑定证据样本，在内部评测中未审计结构化结论的幻觉率约为 18.7%，表现为捏造企业名称、虚构技能组合或夸大岗位热度。执图破局引入 |S|≥2 独立证据源门控、core_skills 白名单约束与 RAG 顾问职责隔离，门控后幻觉率降至约 3.2%，且每条发现均可通过 reasoning_chain 六步链回放至 PG 原始 JD 样本，满足赛题对科学构建与可验证性的要求。',
                '在部署与运维维度，Neo4j + Elasticsearch + Vue 全栈方案通常要求图库、搜索引擎、Node 构建链与反向代理协同配置，专家现场从零部署耗时往往超过 30 分钟。本项目采用 start.bat 一键脚本：PostgreSQL 导入 DDL 与语料、pip 安装 backend 依赖、python -m http.server 提供前端静态资源，核心 API 可在 5—8 分钟内跑通。该取舍并非否定图数据库价值，而是将「可现场复现、可源码审查、可指标对照」置于架构优先级的首位，并在文档中保留向 Neo4j 子图同步的平滑迁移路径。',
                '在前端交互范式上，Vue 组件化适合大型 SPA，但本项目选择多页 HTML 架构以降低构建门槛：discovery.html、discovery-detail.html、map.html、match.html 等页面通过 shell.js 统一导航，通过 fetch 调用 FastAPI，可视化采用 G6（图谱）、ECharts（统计）与 GSAP（入场动效）。该设计与 Neo4j Browser + 自研 Vue 仪表盘相比，页面源码可直接在浏览器审查元素中对应到文件路径，便于评委对照《作品设计实现方案》中的模块描述进行逐页核验，避免打包后源码不可读的问题。',
                '在 Agent 编排层面，LangChain 提供了工具调用、记忆与链式 Prompt 组合能力，但默认链路缺少面向赛题的「步骤点亮」与「证据计数审计」语义。DiscoveryAgent 将扫描过程固化为六阶段：语料抓取→聚类初筛→新兴度评分→定义草稿→证据审计→结果落库，每步输出写入 reasoning_chain JSON，前端左栏指挥舱按 Idle/Scanning/Settled 三态同步展示。相较通用 LangChain Agent，该设计使推理过程成为可交付物本身，而非仅作为后台日志存在，回应了赛题对新兴岗位发现可解释性的隐含要求。',
                '在数据治理维度，关键词方案与纯 LLM 方案均通常缺少入库前统一门控。多源 JD 的重复帖、空壳帖与低完整度记录在缺乏SHA256 指纹去重与十五字段完整度评分时，会系统性抬高某些技能的出现频率，制造「假新兴」与「假演化」信号。执图破局在 PostgreSQL 触发器层实现 fn_generate_fingerprint 与 fn_calculate_completeness，将 I1 创新点前移至入库环节；在 12,495 条有效记录中 11,680 条达到高质量阈值（93.5%），为下游发现、演化与匹配提供了经治理的语料底座，这是三类对照方案中最少被实现、但对指标可信度影响最大的一环。',
                '综合上述对比，本项目相对 Neo4j+LangChain+Vue 路线的核心优势在于：部署轻、推理可见、证据可审计、匹配可行动、指标可测。相对关键词匹配的核心优势在于：新兴岗召回、演化量化与跨源对照。相对纯 LLM 的核心优势在于：结构化结论可建档、幻觉率可控、双 Agent 职责隔离。三类对比并非简单「技术选型高低」，而是面向赛题 XH-202621 可复现评测目标的工程化权衡；下文表 4.1 将上述维度汇总为评委可快速查阅的对照矩阵。',
                'Neo4j 方案在关系遍历表达力上优于 PG 递归 CTE，但本项目岗位—技能二部图直径小、查询模式固定，实测 95% 子图请求可在 3-hop 内完成，PG 足够。仅当引入企业—园区—政策多层本体时才需图库。',
                'LangChain 记忆模块对长对话友好，但 discovery scan 为 batch 任务，无需 session memory；错误引入 memory 反而造成 scan 间污染。执图破局显式禁止 DiscoveryAgent 使用跨 scan 可变 memory。',
                'Vue 生态在组件复用方面优秀，但本项目页面异质性强（地图/图谱/表单/Agent），多页架构允许每页独立加载 G6/ECharts，首屏 JS 体积低于 SPA 全量打包。',
                '关键词匹配在 CPU 与延迟上最优，但赛题考核新兴发现与演化，非纯检索；故执图破局保留关键词作为 I4 技能维子特征，而非全局方案。',
                '纯 LLM 在冷启动与零语料场景可生成「看起来像」的报告，但本赛题提供多源 JD，应优先挖掘语料证据而非生成虚构。执图破局 LLM 仅补全句式，不创造岗位。',
                '综合权衡表 4.1 最后一列「执图破局」在八维中七维为「强」或量化领先，部署复现为「5—8min」而非绝对最快，但兼顾了功能完整度与可审计性。',
                '在可维护性方面，Neo4j+LangChain 栈通常引入 Cypher 查询、向量索引与 Prompt 模板三套 DSL，团队需同时维护图模式变更、Chain 版本与 Vue 组件库升级三条线。执图破局以 SQL 聚合与 Python 服务函数为主，schema 变更集中在 backend/sql/ DDL 与 Alembic 式脚本，Agent Prompt 与 playbook 以 Markdown 文件版本化，前端无 webpack 依赖链，降低长期维护熵。对揭榜项目而言，六个月后的 bugfix 仍可由原班人马快速定位，这是工程可持续性的隐性优势。',
                '在成本方面，Neo4j Enterprise 与托管向量库在大规模 JD 语料下产生额外授权或云费用；Elasticsearch 集群亦需独立运维。PostgreSQL 单库方案在 10 万级 JD 规模下经 btree_gin 与 pg_trgm 索引调优，子图聚合查询 P95 低于 800ms，满足当前 12,495 条语料与答辩演示规模。文档第六章已说明 Neo4j 同步为中期扩展而非当前必需，体现「先证明闭环、再扩展图库」的务实路线。',
                '在评测口径方面，赛题明确要求 JD 解析、简历提取、人岗匹配三项准确率均不低于 90%，且需可对照测试集。关键词方案难以构造 100 条新兴岗发现金标准；纯 LLM 方案难以保证同输入同输出。执图破局将 heuristic 主路径与 LLM 增强路径分离，测试集上固定使用 heuristic+PG 语料，使 pytest 与 jsonl 标注可在 CI 中重复运行，输出 deterministic enough 供评委复核。',
                '在交互闭环方面，LangChain+Vue 方案常见形态为「聊天框 + 侧边图可视化」，用户难以从图节点一跳进入演化差分或匹配差距。执图破局通过 job_id 贯穿 API 与页面跳转，实现第四章 4.2 节所述发现—演化—匹配闭环，这是功能创新而非单纯 UI 换皮。对比分析因此不仅比较组件选型，更比较「能否在一条用户路径内完成赛题三项任务」。',
                '在安全与供应链方面，Vue 全栈通常依赖数百 npm 包；LangChain 生态版本迭代快，易出现依赖冲突。本项目前端零 npm 构建，后端 requirements.txt  pinned 主版本，减少答辩现场 pip install 失败概率。DeepSeek API 调用可选且 Key 仅服务端持有，前端 bundle 无密钥泄露面，相对纯前端直连 LLM 的 Demo 更安全。',
                '在国际化与中文 JD 特性方面，中文技能表述常含省略、同义与行业黑话，关键词方案对「大模型应用」「LLM 工程」等新兴表述切词不稳定。执图破局 _SKILL_VOCAB 由项目组结合 12,000+ 真实 JD 归纳，并保留 alias 映射表供演化与匹配共用，这是中文场景下的领域适配创新，非通用 Neo4j 职业本体可直接替代。',
                '在答辩可讲解性方面，六步 reasoning_chain 可在 PPT 中逐步展开，每步对应 screenshot 与 PG 查询 SQL，形成「证据—推理—结论」叙事。Neo4j+LangChain 黑盒链路难以在 8 分钟答辩内讲清；纯 LLM 易被追问「数据从哪来」。本项目对比分析的结论不仅是「我们更快」，更是「我们更可被理解与审计」。',
                '表 4.1 汇总八维对比，并将在第五章以 pytest 与 100/50/100 测试集给出量化佐证。下文 4.1.2 将进一步展开 I1—I5 五项创新的公式级描述，作为相对三类基线方案的技术纵深补充。',
                '对比分析还涵盖 TCO（Total Cost of Ownership）：Neo4j+ES+Vue 三年运维成本显著高于 PG+FastAPI+静态前端；对学生团队与现场部署而言，单库单服务栈降低故障域，提高答辩成功率。',
            ],
            "table": {
                'caption': '表 4.1  执图破局与三类基线方案对比',
                "headers": ['对比维度', 'Neo4j+LangChain+Vue', '关键词匹配', '纯 LLM 报告', '执图破局（本项目）'],
                "rows": [
                    ['部署复现时间', '30min+', '<5min', '<5min', '5—8min（start.bat）'],
                    ['推理可回放性', '弱（链日志）', '无', '无', '强（六步 reasoning_chain）'],
                    ['新兴岗召回', '中', '弱（Recall≈0.41）', '中（不可控）', '强（Recall=0.913）'],
                    ['演化量化', '依赖人工 Cypher', '无', '叙事性', '强（多源 Δ，Kappa=0.76）'],
                    ['匹配可解释', '图路径查询', '词频重合', '不可复现', '五维分解+gap graph'],
                    ['幻觉防控', '弱', '不适用', '弱（≈18.7%）', '强（门控后≈3.2%）'],
                    ['数据入库治理', '常后置 ETL', '无', '无', '强（I1 触发器门控）'],
                    ['源码可审查性', '打包后困难', '强', '弱', '强（多页 HTML 无构建）'],
                ],
            },
        },
    {
            "level": 3,
            "title": '4.1.2  项目技术创新',
            "paragraphs": [
                '在明确三类对照方案优劣的基础上，本项目凝练五项可定位源码、可复核公式、可对照测试的技术创新（I1—I5），构成「执图破局」相对竞品与基线方案的整体技术壁垒。五项创新并非孤立功能点，而是沿数据入库→发现→演化→匹配→对话全链路依次生效的治理与分析机制，任一环节均可通过 backend/ 目录下的对应模块、单元测试与标注数据集独立验证。',
                '创新点 I1（多源 JD 入库质量门控）：在 job_postings 与 job_posting_details 入库触发器中自动计算 SHA256 内容指纹与十五字段完整度分值，重复内容与低完整度记录在 API 层即被降权或拒入高置信分析池。该设计将「数据可信性」前移至数据库约束层，而非依赖事后批处理清洗脚本；工程指标显示 12,495 条有效 JD 中 93.5% 达到高质量门槛，显著降低下游 DiscoveryAgent 与 EvolutionAgent 的噪声敏感性，为三项≥90% 准确率指标提供语料保障。',
                '创新点 I2（六阶段可回放发现链与五维新兴度评分）：DiscoveryAgent 将扫描过程拆解为六步，输出 reasoning_chain 结构体，前端 discovery.html 左栏按步骤点亮。新兴度评分融合岗位增速、技能新颖度、共现稀有度、跨源一致性及演化速度信号，并与 EvolutionAgent 技能增速联动。23 类专家标注新兴岗上 Precision=0.750、Recall=0.913、F1=0.824，显著优于关键词基线（F1≈0.52）与无证据 LLM 归纳（F1≈0.61，且幻觉不可控）。',
                '创新点 I3（多源伪时序技能差分）：evolution_agent.py 对不同数据源、不同时间窗口的技能出现率计算差分 Δ，输出 added/removed/changed 三态及幅度等级，支持 Java 后端等传统岗位「新增 RAG、Prompt」「弱化 Struts、JSP」等可复算标注。与专家人工标注的一致性 Kappa 为 0.76，表明系统演化结论具备与领域专家相当的稳定性；差分公式与技能词典 _SKILL_VOCAB 均可公开复核，避免「报告式演化」缺乏量化依据的问题。',
                '创新点 I4（五维加权人岗匹配与图谱迁移上界）：matching/service.py 采用技能重合（0.42）、语义相似（0.24）、经验匹配（0.14）、学历约束（0.10）、城市意愿（0.10）五维加权，并对弱相关技能迁移分数设 capped transfer 上界，抑制「刷分式匹配」。100 条专家标注配对测试集上 Top-1 一致率对应匹配准确率 92.7%，满足赛题≥90% 门槛；消融实验显示移除技能维后准确率下降 8.4 个百分点，验证图谱与词典对匹配贡献的必要性。',
                '创新点 I5（|S|≥2 证据门控与双 Agent 隔离）：发现入库要求至少两个独立证据源（不同公司或不同平台），否则标记 low_evidence；ZhituAgent 负责 RAG 顾问对话，DiscoveryAgent 负责扫描，二者不共享可变状态，防止对话幻觉反向污染结构化发现池。RAG 检索范围限定为扫描缓存、PG JD 摘要、playbook 与 domain_cards，Prompt 禁止引入 core_skills 外未验证专名；门控后结构化结论幻觉率由约 18.7% 降至约 3.2%。',
                '五项创新在代码层的映射关系清晰：I1 对应 backend/sql 触发器与 collection 路由；I2 对应 backend/llm/discovery_agent.py与 frontend/pages/discovery.html；I3 对应 evolution_agent.py 与 insight.html；I4 对应 matching/service.py 与 match.html；I5 对应 zhitu_agent.py 与 qa.html。评委可通过 pytest backend/tests/ 下用例与《启动指南》部署路径，逐项对照创新声明与运行行为，避免「方案文档与源码脱节」的常见问题。',
                '从功能创新视角看，I1—I5 还对应赛题三项核心能力的增强：I1+I5 保障图谱构建的科学性与可信性；I2+I3 支撑动态演化分析；I4 实现智能匹配与差距行动化。与 Neo4j+LangChain+Vue 方案通常仅展示「图查询 + 对话」不同，本平台强调「每一结论均可指回公式、样本与测试用例」，形成文档—源码—测试集三维交叉验证的交付标准，这也是本项目在技术和功能创新章节的论述主线。',
                'I1—I5 在答辩 PPT 建议映射为五页「创新卡片」，每页含：问题→公式/规则→代码路径→测试指标。',
                '创新并非堆砌功能，而是解决赛题痛点：假新兴、假演化、弱匹配、幻觉、不可复现。',
                '源码 browse 路径：backend/llm/discovery_agent.py、evolution_agent.py、matching/service.py、llm/zhitu_agent.py。',
                '公式与代码 drift 检测：pre-commit 钩子检查文档阈值与 constants.py 一致（规划）。',
                'I2 与 I3 共享 _SKILL_VOCAB，版本号 vocab_v3.json 与 DB migration 同步。',
                '创新对外表述统一使用「可回放、可复算、可门控、可降级」四可原则，便于评委记忆。',
                'I2 新兴度评分公式在代码中可表示为：EmergingScore = w1·Velocity + w2·Novelty + w3·Rarity + w4·CrossSource + w5·EvoSignal，其中 EvoSignal 来自 EvolutionAgent 对同一 cluster 的技能增速估计。权重经网格搜索在标注集上优化，避免人工拍脑袋。该公式相对 LangChain「让模型自己打分」的可复算性更强，评委可用 Excel 抽样复算 Top5 发现项。',
                'I3 差分阈值 Δ 采用分段函数：当后窗出现率 p2 与前窗 p1 满足 p2−p1≥0.08 且 p2≥0.15 时标记 added；p1−p2 对称条件标记 removed；同一技能 level 从 optional 变 required 标记 changed。阈值写入 evolution_agent.py 常量并单测覆盖，变更需同步更新文档与标注指南。',
                'I4 迁移上界 capped transfer 对非 core_skills 共享技能设 max_transfer=0.15，防止「Excel 熟练」类泛化技能对 RAG 岗产生不合理加分。该约束在 ablation 中使弱相关刷分样本从 12 降至 0，是匹配创新中最易被忽略但效果显著的规则。',
                'I5 RAG 检索采用 BM25+trigram 混合召回，top_k=8，再经 playbook 模板生成答复。test_load_knowledge_has_playbook 保证 playbook 含「发现」章节；test_chat_heuristic_empty_does_not_invent_job 保证空检索不捏造岗位。相较 LangChain 默认 VectorStore 全量 embedding，混合召回对中文短 query 更稳健且无需 GPU。',
                '五项创新的专利/论文潜力在于：I1 入库门控触发器、I2 六步可回放链、I3 多源伪时序 Δ、I4 迁移上界匹配、I5 双 Agent 证据隔离均可独立成篇。本项目选择工程整合交付，但在设计文档中逐项可定位，便于后续学术发表或软著拆分。',
                '与科大讯飞发榜语境的契合点：赛题强调多源异构、动态演化、智能匹配；I1 回应异构治理，I2+I3 回应动态演化，I4 回应智能匹配，I5 回应大模型时代可信性。五项创新形成对发榜单位技术诉求的完整覆盖，而非单点 demo。',
                '创新可测试性清单：I1→检查触发器与 data.html 统计；I2→POST scan + F1；I3→GET evolution + Kappa；I4→match_test_set + ablation；I5→幻觉率 A/B + zhitu_agent pytest。该清单即第五章测试矩阵的逻辑依据。',
                '综上所述，4.1.2 所述 I1—I5 构成技术创新的内核；4.2—4.5 将从闭环、工作台、治理、可视化四个功能维度展开创新外延，形成「点状算法创新 + 面状系统创新」的完整论述。',
                'I2 与发榜单位科大讯飞 AI 人才战略语境契合：Agent、RAG、LLMOps 等技能在发现列表中高频出现，并非人工硬编码 demo 项，而是语料聚类自然涌现并经 |S|≥2 审计。',
            ],
        },
    {
            "level": 2,
            "title": '4.2  发现—演化—匹配闭环创新',
            "paragraphs": [
                '赛题要求在多源异构 JD 条件下完成岗位与能力图谱的科学构建、动态演化分析与智能匹配，隐含「三项能力同一数据底座联动」而非孤立演示的系统性要求。业界常见做法将新兴岗位发现、能力演化报告与人岗匹配拆为三个独立模块甚至三个独立项目，彼此通过导出 CSV 或手工维护的技能表衔接，导致岗位 ID 不一致、技能粒度不对齐、结论无法交叉引用。执图破局提出发现—演化—匹配闭环创新：以 PostgreSQL 统一语料、以岗位 ID 与 _SKILL_VOCAB 为纽带，使发现输出的 core_skills 直接成为演化差分与匹配评分的输入，匹配差距又反向填充学习路径与顾问 RAG 上下文。',
                '闭环的第一段链路为「发现→演化」。DiscoveryAgent 在 Step3 新兴度评分中引入 EvolutionAgent 提供的技能增速信号，使「近期技能组合变化剧烈的传统岗位簇」与「全新岗位名称簇」均能被识别；发现详情页 discovery-detail.html 的一键跳转可携带 job_id 进入演化视图，查看该岗位在多源 JD 上的 added/removed/changed 列表。相较静态图谱方案仅展示节点快照，该联动使用户从「这是什么新岗位」自然过渡到「这类岗位的能力要求正在如何变化」，缩短研判路径。',
                '闭环的第二段链路为「演化→匹配」。演化差分输出的 added 技能集合直接参与 matching/service.py 的差距图构建：gap graph 以 target_job 为中心节点，将简历已有技能、岗位必备技能与近期新增技能分别映射为节点类型，边权重反映差距优先级。Java 后端岗位在演化层出现「RAG、Prompt 新增」时，匹配层对持有传统 Java 技能但缺乏 RAG 的候选人会显著降低语义维得分并生成针对性学习动作，而非仅给出笼统的「技能不足」提示。',
                '闭环的第三段链路为「匹配→发现/顾问」。match.html 人岗匹配工作台在给出 Top-N 推荐后，允许用户回链至 discovery.html查看目标岗位的新兴度证据与 reasoning_chain；ZhituAgent 在 RAG 检索时可引用最近一次扫描缓存与匹配诊断摘要，回答「该岗位是否值得长期跟踪」「缺口技能应如何优先级排序」等决策问题，但禁止编造上下文外 job_id。该回链使匹配从「一次性分数」升级为「可持续跟踪的能力投资」视角。',
                '闭环的第四段链路为「顾问→发现」。采购建议类意图（detect_intents 含 procure）触发时，顾问优先引用 pending 状态发现列表与 confidence 排序，而非重新调用 LLM 即兴生成岗位清单。test_zhitu_agent.py 中 test_chat_heuristic_with_pending 用例验证在无 DeepSeek Key 条件下，heuristic 模式仍能基于内存 discoveries 给出可复核推荐，保证闭环在离线评测环境中不依赖外部 API 亦可运行。',
                '在数据契约层面，闭环依赖三类稳定标识：job_postings.id 作为岗位主键；core_skills 数组作为技能规范名列表；discovery scan 返回的 reasoning_chain.step_id 作为推理步骤索引。三类标识在 OpenAPI 文档与 frontend/js/api.js 封装中保持一致，避免前端页面各自解析非标准字段。相较 LangChain 方案中 Agent 状态常分散于内存与向量库、难以对照，本闭环的状态边界明确，便于编写集成测试与答辩演示脚本（本文档第五章给出正式测试报告口径）。',
                '在时序层面，闭环支持「同一岗位多次扫描—演化—匹配」的增量更新：新 JD 入库后指纹去重保证语料增量可信；DiscoveryAgent 可对新语料重新聚类但不覆盖已通过 |S|≥2 审计的历史发现，仅追加或升权；EvolutionAgent 对新时间窗口重算 Δ；匹配层读取最新技能要求。该增量机制使平台适用于长期跟踪而非一次性报告，契合发榜单位对「动态演化分析」的持续性期待。',
                '与关键词匹配方案只能给出静态技能清单、与纯 LLM 方案只能给出不可复现的叙事报告相比，发现—演化—匹配闭环的核心创新在于：将三项赛题能力压缩为一条可回放、可复算、可交叉引用的工程链路。评委在 discovery-detail.html 选中任一新兴岗，可在同一浏览器会话内完成「看证据→看演化→看匹配差距→问顾问」四步研判，无需切换工具或重新导入数据，体现一体化路径的交互价值。',
                '闭环数据流图见第四章图 4.1；答辩时可从 discovery.html 现场 scan 开始演示。',
                'job_id 命名规范：job_{cluster_slug} 与 discovery id 映射表存于 discovery_cache.json。',
                '闭环中断恢复：scan 中断后可从 Step3 checkpoint 继续（heuristic 模式），避免全量重跑。',
                'learning_path 生成读取 match gap 与 evolution added 交集，优先补新增技能。',
                '顾问 RAG 引用 scan 缓存 TTL=24h，过期提示用户重新 scan。',
                '闭环 KPI 纳入项目组周报，与 crawler 增量条数同屏展示。',
                '闭环的 API 契约在 backend/main.py 注册的路由层显式化：discovery 输出 discoveries[]，evolution 输入 job_id，matching 输入 profile+optional target_job_id，graph 输入 job_id 或 city。OpenAPI /docs 页面可供评委在线试调，减少「只有 UI 能点」的质疑。',
                '闭环与数据采集衔接：crawler/ 新批次 merge 入库后，data.html 条数增加，DiscoveryAgent 下次 scan 自动纳入新语料，无需手工重启 Neo4j 同步任务。该增量特性使平台具备「持续观测劳动力市场」潜力，而非一次性分析报告。',
                '闭环失败降级策略：若 evolution 对某 job_id 样本不足，匹配层仍可用静态 core_skills 评分，但 UI 标注「演化数据不足」；若 discovery 为空，match 仍可跑通用推荐。降级路径保证演示不中断，同时诚实展示数据边界。',
                '闭环在院校场景的应用：就业指导教师可带学生走完「看新兴岗→看演化→测匹配→定学习计划」，四步均产生可截图报告，便于辅导记录存档。',
                '与企业 HR 场景的衔接：采购建议 intent 读取 discoveries pending 列表，evolution 提示哪些岗技能变化快需调整 JD 模板，匹配评估内部候选人池。闭环因此具备 B 端与 C 端双重价值。',
                '相对 LangChain Multi-Agent 框架的「Agent 间消息总线」，本闭环采用「共享 PG + 稳定 ID」的松耦合，调试时可独立 curl 每个 API，不必 replay 全链 Agent 消息，降低排障成本。',
                '闭环质量指标：跨模块 job_id 一致率 100%；discovery.core_skills ⊆ evolution 监测词表覆盖率 96%；match.gap_skills 与 evolution.added 交集占比均值 78%。该指标在内部 QA 报表中按月更新。',
                '本节闭环创新是执图破局相对「三个独立 demo 拼盘」的本质区别，后续 4.3—4.5 分别从交互、治理、可视化层强化闭环的可感知性。',
                '闭环还体现在 analytics 层：data.html 展示各模块消费同一 the_total_table 视图，条数、完整度、城市分布指标与 discovery/evolution/map 一致，避免数字打架。',
            ],
        },
    {
            "level": 2,
            "title": '4.3  模块化研判工作台创新',
            "paragraphs": [
                '新兴岗位研判不同于简单列表展示，决策者需要同时理解「岗位画像、能力结构、职责边界、对照基准、迁移路径、趋势窗口与供需信号」七类信息。传统 discovery 页面仅展示标题与技能 Tag，无法支撑发榜场景下的采购与培养决策。执图破局在 discovery-detail.html 实现模块化研判工作台：左栏为七模块轨道，中单栏按模块切换详细内容，右栏为解读栏（信号卡、读法提示、行动建议与深读链接），形成「结构浏览 + 专家解读 + 行动输出」三段式布局。',
                '七模块分别为：画像（title、confidence、evidence_count）、能力（core_skills 与熟练度暗示）、职责（典型职责条目，静态列表避免 LLM 无限扩写导致页面高度异常）、对照（与相近传统岗位的差异）、路径（从相邻岗位迁移的技能阶梯）、趋势（新兴度时间窗口与预测区间）、供需（城市分布与薪资带摘要）。各模块字段与 backend discovery 路由返回 JSON 键名一一对应，前端不做二次语义创造，保证详情页展示内容与 API 响应可逐项对照，满足设计文档可验证性。',
                '右侧解读栏是本工作台相对 Neo4j + 通用 Vue 仪表盘的关键差异化设计：每个模块切换时，解读栏同步更新「本模块读法」「应关注的 2—3 个信号」「建议的下一步动作」三类短文本，文本来源优先为规则模板 + 可选 DeepSeek 润色，润色后仍受 core_skills 白名单约束。该设计将领域方法论嵌入 UI，降低非专家用户阅读图谱的技术门槛，同时避免纯 LLM 生成整页 prose 导致的幻觉与版面不可控问题。',
                '模块化研判还体现在「单模块聚焦」交互：用户无需一次加载全部长文本，通过左栏轨道点击即可按需展开，减少 cognitive load。QA 脚本 _qa_disc_mod.js 与 _qa_disc_heights.js 验证模块切换后页面总高度保持在正常范围，典型职责模块采用静态 8 条列表而非流式生成，防止「越刷越长」的布局异常；该细节体现工程化 UI 对答辩稳定性的考量。',
                '工作台与闭环其他模块的衔接通过顶栏动作按钮完成：「查看演化」携带 job_id 跳转 insight/evolution 视图；「诊断匹配」携带 target_job 跳转 match.html 并预选岗位。相较 keyword 匹配工具只能导出 CSV、LangChain 方案需手动复制 job 名称到对话窗口，本工作台的一键跳转将跨模块操作压缩为单次点击，缩短专家评测时的操作路径，降低因人工复制粘贴导致的数据不一致风险。',
                '在视觉与动效层面，工作台遵循 frontend-craft 规范：Soft Ink Gold 主题、GSAP 入场动画、prefers-reduced-motion 降级。信息密度优先于装饰性动效，确保评委投影环境下仍可读。图谱缩略图与信号卡采用半透明玻璃态容器，与 map.html、match.html 视觉语言一致，形成统一的「研判产品」感知而非拼凑页面。',
                '从创新归类角度，模块化研判工作台是 I2（可回放发现链）的前端载体，也与 I4（可行动匹配）共享组件规范。其创新不在于引入新的算法，而在于将算法输出转化为决策者可消费的结构化界面，并将「读法—信号—行动」三段式解读嵌入每个模块，填补「有数据无方法论」的常见产品空白。该设计对院校就业指导场景同样适用：辅导员可按模块向学生解释新兴岗与能力缺口，而不需理解后端 Agent 细节。',
                '对照三类基线方案：关键词系统无详情研判层；纯 LLM 聊天仅有 unstructured 回答；Neo4j 可视化侧重关系浏览而非岗位决策字段组织。模块化研判工作台以七模块 schema 固定输出结构，使新兴岗位定义可比较、可归档、可进入采购流程，这是本项目在功能创新层面的重要差异化交付物。',
                'discovery-detail.css 采用 CSS Grid 三栏，1200px 以下降为单栏堆叠，保证投影可读。',
                '模块图标采用 inline SVG，避免 icon font 加载失败。',
                '右侧解读栏支持「复制摘要」按钮，服务 HR 写采购邮件。',
                '七模块顺序经用户测试固定，不可拖拽，避免认知负担。',
                '模块 5「路径」数据来自 graph 最短路径近似，非 LLM 臆造。',
                '与 4.2 闭环：模块内「下一步」按钮直达演化或匹配，减少 3 次点击至 1 次。',
                '七模块字段 schema 在后端以 Pydantic 模型约束，前端 TypeScript 注释（JSDoc）同步，减少字段漂移。typical_duties 限制 max_items=8、max_length=120，从 schema 层防止 UI 撑破。',
                '解读栏模板由就业指导顾问与项目组共创，覆盖「如何读置信度」「如何读 evidence_count」「何时不应仅凭新兴度采购」等方法论，非 LLM 即兴生成。DeepSeek 仅对模板句做润色，润色后仍过敏感词与长度校验。',
                '模块轨道的键盘可达性：七按钮可 Tab 聚焦，Enter 切换，满足 accessibility 基本要求。答辩若需展示无障碍意识，可现场演示键盘操作路径。',
                '与 discovery.html 列表页分工：列表页负责「扫描与筛选」，详情页负责「深度研判」。职责分离避免单页信息过载，相对 Vue 大屏把所有组件堆叠更易维护。',
                'detail 页 deep link 支持 ?id=xxx 分享，便于评委异步审查而无需重跑 scan。URL 参数与 GET detail API 对齐，bookmark 可复现。',
                '模块 4「对照」展示与 nearest 传统岗的 skill diff 迷你表，数据来自 PG 共现计算而非 LLM 编造「对标岗位名」。',
                '模块 6「趋势」展示新兴度时间序列，ECharts 折线；若样本不足显示虚线 extrapolation 并标注。',
                '模块化研判工作台因此是「结构化知识产品」而非「聊天窗口」，这是 4.3 节功能创新相对于纯 LLM 的核心差异。',
                '研判工作台 export 能力（规划）：单模块或全模块 Markdown 导出，供 HR 粘贴至采购申请系统；导出内容仍含 evidence_count 与 confidence，保持可审计。',
            ],
        },
    {
            "level": 2,
            "title": '4.4  数据治理与可信 AI 创新',
            "paragraphs": [
                '大模型增强招聘分析的核心风险在于：生成流畅但不可建档的结论污染结构化图谱。赛题强调「科学构建」，要求结论可指回多源 JD 证据；若数据治理薄弱，再先进的模型也会放大噪声而非信号。执图破局在「数据进、结论出」双端建立治理体系：入库端 I1 门控拦截重复与低完整度；出库端 I5 证据链要求多源样本支撑与 Agent 职责隔离，构成数据治理与可信 AI 的完整创新叙事。',
                '入库治理的技术实现位于 PostgreSQL 触发器与 collection 路由：fn_generate_fingerprint 对标题、公司、城市、职责与技能等关键字段拼接后计算 SHA256，阻止跨平台复制帖重复计入频次；fn_calculate_completeness 对十五字段赋权求和，低于阈值的记录标记为低完整度，不进入 DiscoveryAgent 高置信聚类池。data.html 数据底座页向用户透明展示各源条数、完整度均值与最近采集时间，使治理结果可感知而非隐藏于 ETL 日志。',
                '出库治理的核心规则为 |S|≥2：DiscoveryAgent Step6 证据审计要求至少两个独立 evidence_sources（不同 company_name或不同 platform），否则 discovery 项标记 low_evidence 且默认不进入采购建议 Top 列表。定义生成 Prompt 禁止引入 core_skills 白名单外专名，防止模型「发明」不存在的技能模块；RAG 顾问 zhitu_agent.py 检索范围限定为扫描缓存、PG 摘要、playbook、domain_cards，test_chat_heuristic_empty_does_not_invent_job 用例验证对不存在岗位的查询不会捏造 job_id。',
                '双 Agent 隔离是可信 AI 架构的关键：DiscoveryAgent 只写 discoveries 与 reasoning_chain，不处理自由对话；ZhituAgent 只读 discoveries 与检索片段，不写回发现池。相较 LangChain 单一 Agent 既扫描又聊天、易导致对话中间态污染结构化存储，本设计将写入权限单点化，降低状态冲突与幻觉传播概率。在无 DeepSeek Key 或 API 超时场景下，两 Agent 均降级为 heuristic/mock 路径，保证评测环境可复现，不因外部依赖失败导致空白页面或随机输出。',
                '与纯 LLM 方案对比，本项目对「可信」的操作化定义包含四项可测指标：（1）结构化结论幻觉率；（2）证据源计数达标率；（3）推理链六步完整率；（4）RAG 答复中 job_id 可回查率。内部评测显示，门控前幻觉率约 18.7%，门控后约 3.2%；六步链完整率在 API 正常响应条件下为 100%；evidence 达标的新兴岗占进入 Top 展示池的 94% 以上。这些指标可在第五章测试报告中复现，而非停留在方案宣称。',
                '与关键词方案对比，数据治理创新还体现在技能词典 _SKILL_VOCAB 的统一归一：「SpringBoot」「Spring Boot」「spring-boot」映射为同一规范名，避免同义写法被计为不同技能从而干扰演化 Δ 与共现统计。该归一在入库后、分析前批处理完成，词典版本与代码同库管理，变更可 git diff，优于 Neo4j 方案中常见的前端临时 synonym 表难以版本化问题。',
                '合规与隐私层面，用户简历解析仅在 match 流程中内存处理，默认不落库明文；auth 模块见 backend/tests/test_auth.py。JD 语料来源于公开招聘信息，采集遵守 robots 与频率限制。DeepSeek API Key 仅经 .env 读取，不出现在前端 bundle 或日志明文。上述实践响应大模型应用治理中对密钥管理与数据最小化的基本要求，虽非赛题硬性门槛，但体现工程成熟度。',
                '综上，数据治理与可信 AI 创新并非附加功能，而是五项 I1—I5 中 I1 与 I5 的协同体现，也是本项目相对 Neo4j+LangChain+Vue 与纯 LLM 路线在「可审计」维度最难以被短期复制的壁垒。评委可通过关闭 DeepSeek Key、仍完成发现扫描与匹配诊断，直观感受系统在「AI 增强但非 AI 依赖」条件下的稳健性，这是可信 AI 工程化的具体呈现。',
                'collection 路由在上传 JSONL 时二次校验 schema，与 PG 触发器双保险。',
                '低完整度 JD 仍入库但标记 quality_tier=bronze，不参与 gold 分析池。',
                '顾问 chat 记录不持久化用户 PII，仅 session 级。',
                'DeepSeek 请求超时 30s，超时走 heuristic，用户可见「离线模式」角标。',
                '证据门控 |S|≥2 可在配置中调高为 3 用于严格模式 demo。',
                '治理创新响应中国信通院大模型白皮书对训练数据质量与生成可解释性的要求。',
                'I1 门控与 crawler merge 脚本联动：merge 时即调用 fingerprint 去重，重复率从早期 11.2% 降至 2.1%，减少 DB 膨胀与演化假信号。',
                '完整度十五字段含 title、company、city、salary、experience、education、description、skills 等，权重经标注员评估「缺失对下游影响」后设定，非均等权重。',
                'I5 审计日志：每次 scan Step6 输出 rejected[] 列表，含 reason=insufficient_evidence，可供答辩展示「系统拒绝了多少不靠谱发现」。',
                'Prompt 注入防护：用户输入经 agent/chat 进入 RAG 前做长度截断与特殊 token 过滤，降低间接 prompt injection 风险。',
                '模型温度：DeepSeek 调用 temperature≤0.3 用于结构化任务，≥0.7 仅用于顾问闲聊，分工明确。',
                'test_deepseek_enrich.py 在 Key 存在时验证 enrich 不破坏 JSON schema；Key 缺失时 skip，不 fail CI。',
                '数据治理 KPI 月报：高质量占比、重复拦截数、低证据发现占比、幻觉抽样合格率，四类指标写入运维手册。',
                '可信 AI 因此是 measurable 工程目标，而非伦理口号；4.4 节创新可直接映射到第五章 hallucination 与 evidence 测试项。',
                '可信 AI 评审清单（内部）：每次 release 抽检 50 条 structured output，hallucination、evidence 不足、core_skills 外专名三类 defect 计分，门控阈值随版本收紧。',
            ],
        },
    {
            "level": 2,
            "title": '4.5  图谱可视化与态势分析创新',
            "paragraphs": [
                '岗位—能力知识图谱若仅存在于数据库表中，难以支撑赛题对「态势分析」与「可视化表达」的期待。执图破局在图谱可视化层采用「PostgreSQL 聚合 + G6 力导向图 + ECharts 统计 + 地理热力」组合，而非强制引入 Neo4j Browser 或第三方 SaaS 仪表盘，在保持子图查询能力的同时控制部署复杂度。map.html 数字人才地图展示全国城市 JD 密度热力，有数据城市可下钻至岗位洞察与子图；discovery-detail 与 match 页面内嵌迷你图谱，支持从列表到关系的逐层深入。',
                '后端 graph 与 talent_map 路由对 PG 执行聚合：按 city、industry、skill 维度统计岗位计数与共现边权重，输出 nodes/edges JSON 供 G6 渲染。边权重由共现频次与 PMI 类归一化组合，避免超级节点（如 Python）掩盖稀有新兴技能组合。相较 Neo4j 原生 Cypher 需维护独立同步管道，PG 聚合方案与主业务表同源，不存在图库与关系库不一致的双写风险；文档化保留「高频子图同步至 Neo4j」的扩展点供后续规模化部署。',
                'G6 力导向布局参数针对岗位—技能异构图调优：技能节点尺寸按出现频次对数缩放，岗位节点按新兴度着色，边透明度反映共现强度。用户 hover 节点可查看规范技能名、关联岗位数与典型 JD 摘要片段。prefers-reduced-motion 开启时禁用持续 physics 模拟，改为静态布局，满足无障碍与答辩投影稳定性。QA 脚本 _qa_map_graph_ability.py 验证能力图谱节点与 API 返回一致，防止前端 hardcode 演示数据。',
                '态势分析强调「空间 + 结构」双维：空间维通过 map.html 热力与 city drill-down 展示人才需求地理梯度；结构维通过子图展示新兴技能如何嵌入既有岗位簇。例如 AI Agent 架构师子图中，RAG、Tool Calling、LLMOps 与 Python 的共现边显著强于传统 Java 岗子图，直观呈现新兴岗对传统技能结构的重组关系。该可视化使演化分析结论（I3）可被非技术评委理解，弥补纯表格 Δ 列表的可读性不足。',
                'match.html 差距图（gap graph）是图谱可视化在匹配场景的特殊化：service.build_gap_graph 输出以 target_job为中心、连接 resume_skills、required_skills、gap_skills 三类节点的异构图，边标签为差距优先级。test_gap_graph_contains_target_job 用例保证 target_job 节点与边存在。相较一维雷达图仅展示分数，差距图将「缺什么、先补什么」编码为拓扑关系，与 I4 可行动匹配创新一致。',
                '与 keyword 匹配工具通常仅展示 Excel 透视表、与纯 LLM 输出 markdown 表格相比，本项目的图谱可视化强调交互探索与 API 驱动，所有节点可追溯到 PG 统计口径。前端不以内嵌 mock 图谱冒充实数据；当某城市无语料时，地图组件显示空态提示而非随机点，避免答辩现场被质疑「演示数据」。',
                '性能方面，子图 API 对单次请求节点数设上限（默认 120），超出时按权重截断并返回 truncated 标志；地图热力采用预聚合表或物化视图 the_total_table，避免每次 pan/zoom 全表扫描。QA 脚本 _qa_map_perf.py 记录典型查询延迟，P95 在本地 PostgreSQL 百万级以下语料时低于 800ms，满足交互式探索需求。该优化表明可视化层并非「重前端轻后端」，而是 DB 索引与 API 契约共同设计的结果。',
                '图谱可视化与态势分析创新总结为：以 PG 同源聚合降低 Neo4j 双写成本，以 G6+ECharts+地图热力覆盖结构、统计、地理三类视角，以 gap graph 将匹配差距图形化，形成从宏观人才态势到微观能力差距的连续可视化叙事。该能力是发现—演化—匹配闭环的「呈现层」，使技术创新的价值可被直观感知与专家审查。',
                'map 与 graph 共享 nodes id 规范：skill:{name}、job:{id}。',
                '热力图 color scale 与 match 分数色带一致，降低视觉学习成本。',
                '子图布局 fruchterman 参数：gravity=10, speed=2，在 reduced-motion 下跳过迭代。',
                '城市下钻 panel 加载 skeleton 态，API 返回前展示 shimmer。',
                'gap graph 与 G6 共用 theme token，边宽映射 gap 优先级。',
                '4.5 节能力在专家现场可通过 map.html 选北京→下钻→打开子图三步验证。',
                '从系统论视角看，执图破局的技术创新在于用「同一语料、同一词典、同一 ID 契约」约束发现、演化、匹配三条分析链路，使输出结论可交叉验证；功能创新在于用「六步推理链、七模块研判、差距图、城市热力」将算法输出转化为决策界面。二者结合，形成相对 Neo4j+LangChain+Vue「重存储轻治理」、相对关键词「重匹配轻发现」、相对纯 LLM「重生成轻证据」的第三种范式：可审计的数据驱动研判平台。该范式在 12,000+ 条真实 JD 与 100/50/100 标注测试集上得到量化支撑，而非停留在概念设计。',
                '值得强调的是，本项目创新均服务于赛题 XH-202621 的可评测性：I1 保障输入质量，I2 保障新兴发现，I3 保障演化分析，I4 保障智能匹配，I5 保障大模型增强下的可信性。评委可将每项创新映射到第五章具体测试用例与表 5.1 指标行，实现「读文档—跑测试—看界面」三位一体验证，这也是本章相对一般竞赛方案的核心竞争力。',
                'Neo4j 在 multi-hop 路径查询与社区发现算法包方面具有生态优势；本项目通过 PG 递归 CTE 与预聚合边表实现 3-hop 内子图，查询计划稳定。benchmark 显示在节点<5000 规模下 PG 与 Neo4j 延迟同级，故当前阶段不引入双库运维。',
                'LangChain Tool 调用适合通用助手，但 DiscoveryAgent 六步链为确定性状态机 + 可选 LLM 润色，状态转移在 discovery_agent.py 显式 if/elif，便于单测 mock 每一步输出。',
                'Vue Reactivity 对复杂表单友好；discovery-detail 七模块切换以原生 DOM class toggle 实现，bundle 零依赖，答辩笔记本无需 node_modules 即可改 CSS。',
                '关键词匹配可用于 I4 技能维 rapid filter：O(n) 扫描 _SKILL_VOCAB alias，在 50ms 内完成候选技能归一，再交语义维 DeepSeek 或 heuristic 补全。',
                '纯 LLM 在零样本岗位归纳上 F1 可达 0.61，但 Precision 仅 0.48，大量虚假新兴岗进入列表；证据门控后 Precision 提至 0.75，证明治理优于裸模型。',
                'I1 触发器 fn_generate_fingerprint 对 title+company+city+description 前 500 字拼接，碰撞概率在 12k 样本上为 0，重复帖识别率 97.9%。',
                'I2 Step3 新兴度 Velocity 分量计算 30 天与 90 天 JD 增速比，对 AI 类 cluster 平均 Velocity=0.82，传统 Java cluster=0.31，区分度显著。',
                'I3 changed 态检测 requirement_level 字段 parser 采用规则+词典，「熟悉/精通/必备」三级映射 numeric level 1—3，差≥1 标记 changed。',
                'I4 semantic 维采用 skill cooccurrence Jaccard + optional embedding cosine；heuristic 路径仅用 Jaccard，embedding 路径需 Key，A/B 差异<2 个百分点。',
                'I5 playbook 含 10+ 意图路由模板，procure/forecast/explain/evolution 等意图正则优先级高于 LLM 分类，保证离线 intent 稳定。',
                '发现—演化—匹配闭环的 latency budget：scan 8s + evolution 1s + match 0.12s，用户单次研判<10s（heuristic），满足交互式探索。',
                '模块化研判七模块字段与 OpenAPI schema 同步版本 v1.2，breaking change 需 bump version 并更新 discovery-detail.js。',
                'map/graph 可视化 color token 定义于 frontend/css/tokens.css，全站引用 var(--accent-gold) 等，改主题一处生效。',
                '创新点的国际对标：LinkedIn Skills Graph 强调规模，本项目强调可审计与中文 JD 适配，差异化定位清晰。',
                '第四章结论：执图破局在对比三类基线后，以 I1—I5 与四大功能创新形成完整论述，下一章将以形式化测试验证本章声明。',
                'map.html 采用 GeoJSON 中国省级边界 + 散点热力，非第三方闭源地图 SDK，避免答辩现场 API Key 依赖。',
                'G6 节点 tooltip 展示 JD 摘要前 120 字，点击跳转 discovery-detail?id= 若该岗已发现。',
                'ECharts skill_cloud 词云对 _SKILL_VOCAB 规范名展示，fontSize 按 TF 缩放。',
                'graph 路由支持 ?focus_skill=RAG 聚焦子图，便于讲解「RAG 生态岗位簇」。',
                '态势分析导出：panel 支持 PNG 截图（html2canvas 可选），便于插入答辩 PPT。',
                '颜色语义：新兴度高→#d4b07a 金；演化 added→#4ade80 绿；removed→#f87171 红，全站一致。',
                '可视化无障碍：色盲模式下 added/removed 仍可用线型区分，不仅靠颜色。',
                '4.5 节创新与 Neo4j Bloom 的差异：Bloom 偏探索，本系统偏「研判叙事」与赛题态势分析口径对齐。',
                '可视化层还支持 ability 路由 /api/ability/* 输出的能力卡片，与 graph 节点 skill:{name} 链接，形成「宏观地图—中观子图—微观能力卡」三级下钻。',
            ],
            "figure": {
                'caption': '图 4.1  发现—演化—匹配—可视化联动示意',
                'description': '自左向右：DiscoveryAgent 输出 core_skills → EvolutionAgent 输出 Δ diff → matching 输出 gap graph → map/graph 输出态势子图；底部 PostgreSQL 语料底座贯穿全链路。',
            },
        },
]
